import type { MarketSymbol } from "../types";

export const US_MARKET_SYMBOLS: MarketSymbol[] = [
  { id: "SPY", symbol: "SPY", name: "SPDR S&P 500 ETF", type: "stock", market: "us", exchange: "NYSE Arca", currency: "USD", dataProvider: "yahoo", price: 548.3, change24h: 0.28, volume24h: 70200000, precision: 2 },
  { id: "QQQ", symbol: "QQQ", name: "Invesco QQQ Trust", type: "stock", market: "us", exchange: "NASDAQ", currency: "USD", dataProvider: "yahoo", price: 477.12, change24h: 0.46, volume24h: 46300000, precision: 2 },
  { id: "DIA", symbol: "DIA", name: "SPDR Dow Jones Industrial Average ETF", type: "stock", market: "us", exchange: "NYSE Arca", currency: "USD", dataProvider: "yahoo", price: 390.2, change24h: 0.18, volume24h: 4200000, precision: 2 },
  { id: "IWM", symbol: "IWM", name: "iShares Russell 2000 ETF", type: "stock", market: "us", exchange: "NYSE Arca", currency: "USD", dataProvider: "yahoo", price: 205.6, change24h: -0.12, volume24h: 31100000, precision: 2 },
  { id: "GLD", symbol: "GLD", name: "SPDR Gold Shares", type: "stock", market: "us", exchange: "NYSE Arca", currency: "USD", dataProvider: "yahoo", price: 217.5, change24h: 0.22, volume24h: 9100000, precision: 2 },
  { id: "SLV", symbol: "SLV", name: "iShares Silver Trust", type: "stock", market: "us", exchange: "NYSE Arca", currency: "USD", dataProvider: "yahoo", price: 28.4, change24h: 0.31, volume24h: 19000000, precision: 2 },
  { id: "TLT", symbol: "TLT", name: "iShares 20+ Year Treasury Bond ETF", type: "stock", market: "us", exchange: "NASDAQ", currency: "USD", dataProvider: "yahoo", price: 92.8, change24h: -0.08, volume24h: 36400000, precision: 2 },
  { id: "USO", symbol: "USO", name: "United States Oil Fund", type: "stock", market: "us", exchange: "NYSE Arca", currency: "USD", dataProvider: "yahoo", price: 76.2, change24h: 0.48, volume24h: 5200000, precision: 2 },
  { id: "^GSPC", symbol: "^GSPC", name: "S&P 500 Index", type: "stock", market: "us", exchange: "SNP", currency: "USD", dataProvider: "yahoo", price: 5487, change24h: 0.31, volume24h: 0, precision: 2 },
  { id: "^IXIC", symbol: "^IXIC", name: "NASDAQ Composite", type: "stock", market: "us", exchange: "NASDAQ", currency: "USD", dataProvider: "yahoo", price: 17689, change24h: 0.45, volume24h: 0, precision: 2 },
  { id: "^DJI", symbol: "^DJI", name: "Dow Jones Industrial Average", type: "stock", market: "us", exchange: "DJI", currency: "USD", dataProvider: "yahoo", price: 39150, change24h: 0.18, volume24h: 0, precision: 2 },
  { id: "^RUT", symbol: "^RUT", name: "Russell 2000 Index", type: "stock", market: "us", exchange: "RUT", currency: "USD", dataProvider: "yahoo", price: 2050, change24h: -0.14, volume24h: 0, precision: 2 },
  { id: "^VIX", symbol: "^VIX", name: "CBOE Volatility Index", type: "stock", market: "us", exchange: "CBOE", currency: "USD", dataProvider: "yahoo", price: 14.2, change24h: 1.7, volume24h: 0, precision: 2 },
  { id: "AMZN", symbol: "AMZN", name: "Amazon.com Inc.", type: "stock", market: "us", exchange: "NASDAQ", currency: "USD", dataProvider: "yahoo", price: 184.91, change24h: 0.34, volume24h: 35600000, precision: 2 },
  { id: "META", symbol: "META", name: "Meta Platforms Inc.", type: "stock", market: "us", exchange: "NASDAQ", currency: "USD", dataProvider: "yahoo", price: 512.7, change24h: 0.52, volume24h: 12100000, precision: 2 },
  { id: "GOOGL", symbol: "GOOGL", name: "Alphabet Inc.", type: "stock", market: "us", exchange: "NASDAQ", currency: "USD", dataProvider: "yahoo", price: 176.11, change24h: 0.18, volume24h: 24200000, precision: 2 },
  { id: "AMD", symbol: "AMD", name: "Advanced Micro Devices Inc.", type: "stock", market: "us", exchange: "NASDAQ", currency: "USD", dataProvider: "yahoo", price: 154.4, change24h: 0.92, volume24h: 61200000, precision: 2 },
  { id: "NFLX", symbol: "NFLX", name: "Netflix Inc.", type: "stock", market: "us", exchange: "NASDAQ", currency: "USD", dataProvider: "yahoo", price: 676.1, change24h: -0.24, volume24h: 3900000, precision: 2 },
  { id: "AVGO", symbol: "AVGO", name: "Broadcom Inc.", type: "stock", market: "us", exchange: "NASDAQ", currency: "USD", dataProvider: "yahoo", price: 1680, change24h: 0.64, volume24h: 3900000, precision: 2 },
  { id: "JPM", symbol: "JPM", name: "JPMorgan Chase & Co.", type: "stock", market: "us", exchange: "NYSE", currency: "USD", dataProvider: "yahoo", price: 202.4, change24h: 0.16, volume24h: 8800000, precision: 2 },
  { id: "XOM", symbol: "XOM", name: "Exxon Mobil Corp.", type: "stock", market: "us", exchange: "NYSE", currency: "USD", dataProvider: "yahoo", price: 113.2, change24h: -0.14, volume24h: 16100000, precision: 2 },
  { id: "MSTR", symbol: "MSTR", name: "MicroStrategy Inc.", type: "stock", market: "us", exchange: "NASDAQ", currency: "USD", dataProvider: "yahoo", price: 1450, change24h: 1.24, volume24h: 2100000, precision: 2 },
  { id: "COIN", symbol: "COIN", name: "Coinbase Global Inc.", type: "stock", market: "us", exchange: "NASDAQ", currency: "USD", dataProvider: "yahoo", price: 248.5, change24h: 0.92, volume24h: 8500000, precision: 2 },
  { id: "PLTR", symbol: "PLTR", name: "Palantir Technologies Inc.", type: "stock", market: "us", exchange: "NYSE", currency: "USD", dataProvider: "yahoo", price: 24.7, change24h: 0.78, volume24h: 42000000, precision: 2 },
  { id: "ORCL", symbol: "ORCL", name: "Oracle Corp.", type: "stock", market: "us", exchange: "NYSE", currency: "USD", dataProvider: "yahoo", price: 139.6, change24h: 0.2, volume24h: 8300000, precision: 2 },
  { id: "CRM", symbol: "CRM", name: "Salesforce Inc.", type: "stock", market: "us", exchange: "NYSE", currency: "USD", dataProvider: "yahoo", price: 242.8, change24h: -0.16, volume24h: 6800000, precision: 2 },
  { id: "QCOM", symbol: "QCOM", name: "Qualcomm Inc.", type: "stock", market: "us", exchange: "NASDAQ", currency: "USD", dataProvider: "yahoo", price: 205.8, change24h: 0.35, volume24h: 9800000, precision: 2 },
  { id: "INTC", symbol: "INTC", name: "Intel Corp.", type: "stock", market: "us", exchange: "NASDAQ", currency: "USD", dataProvider: "yahoo", price: 31.2, change24h: -0.28, volume24h: 51000000, precision: 2 },
  { id: "TSM", symbol: "TSM", name: "Taiwan Semiconductor ADR", type: "stock", market: "us", exchange: "NYSE", currency: "USD", dataProvider: "yahoo", price: 172.4, change24h: 0.62, volume24h: 15600000, precision: 2 },
  { id: "ASML", symbol: "ASML", name: "ASML Holding NV ADR", type: "stock", market: "us", exchange: "NASDAQ", currency: "USD", dataProvider: "yahoo", price: 956.7, change24h: 0.41, volume24h: 1200000, precision: 2 },
  { id: "V", symbol: "V", name: "Visa Inc.", type: "stock", market: "us", exchange: "NYSE", currency: "USD", dataProvider: "yahoo", price: 276.2, change24h: 0.11, volume24h: 7100000, precision: 2 },
  { id: "MA", symbol: "MA", name: "Mastercard Inc.", type: "stock", market: "us", exchange: "NYSE", currency: "USD", dataProvider: "yahoo", price: 455.3, change24h: 0.14, volume24h: 2600000, precision: 2 },
  { id: "LLY", symbol: "LLY", name: "Eli Lilly and Co.", type: "stock", market: "us", exchange: "NYSE", currency: "USD", dataProvider: "yahoo", price: 887.2, change24h: 0.36, volume24h: 3200000, precision: 2 },
  { id: "NVO", symbol: "NVO", name: "Novo Nordisk ADR", type: "stock", market: "us", exchange: "NYSE", currency: "USD", dataProvider: "yahoo", price: 132.9, change24h: 0.24, volume24h: 5200000, precision: 2 }
];
